# sudo dnf in wayfire mate-polkit xdg-desktop-portal-wlr wdisplays brightnessctl playerctl

[animate]
#close_animation = fire

[autostart]
0_environment = dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XAUTHORITY XDG_CURRENT_DESKTOP
2_systemctl = systemctl --user unset-environment INSTALL4J_ADD_VM_PARAMS
autostart0 = /usr/libexec/polkit-mate-authentication-agent-1
autostart_wf_shell = true
portal = /usr/libexec/xdg-desktop-portal

[command]
binding_copilot = <shift> <super> KEY_F23
binding_emoji = <super> KEY_DOT
binding_explorer = <super> KEY_E
binding_mic_mute = KEY_MICMUTE
binding_pause = KEY_PLAYPAUSE
binding_screenshot = KEY_SYSRQ
binding_screenshot_interactive = <shift> <super> KEY_S
binding_task_manager = <shift> <ctrl> KEY_ESC
binding_terminal = <super> KEY_ENTER
binding_volume_mute = KEY_MUTE
command_brightness_down = brightnessctl set 5%-
command_brightness_up = brightnessctl set +5%
command_copilot = /usr/bin/flatpak run --command=alpaca com.jeffser.Alpaca
command_emoji = flatpak run com.tomjwatson.Emote
command_explorer = dolphin
command_mic_mute = wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
command_pause = playerctl play-pause
command_screenshot = grim $(xdg-user-dir PICTURES)/Screenshots/$(date '+%F_%Hh%Mm%Ss').png
command_screenshot_interactive = slurp | grim -g - $(xdg-user-dir PICTURES)/Screenshots/$(date '+%F_%Hh%Mm%Ss').png
command_task_manager = /usr/bin/flatpak run --command=missioncenter io.missioncenter.MissionCenter
command_terminal = xdg-terminal-exec
command_volume_down = wpctl set-volume @DEFAULT_SINK@ 5%-
command_volume_mute = wpctl set-mute @DEFAULT_SINK@ toggle
command_volume_up = wpctl set-volume @DEFAULT_SINK@ 5%+ --limit 1.0
repeatable_binding_brightness_down = KEY_BRIGHTNESSDOWN
repeatable_binding_brightness_up = KEY_BRIGHTNESSUP
repeatable_binding_volume_down = KEY_VOLUMEDOWN
repeatable_binding_volume_up = KEY_VOLUMEUP

[core]
plugins = alpha animate autostart command cube decoration fast-switcher foreign-toplevel grid gtk-shell idle move oswitch place resize session-lock shortcuts-inhibit switcher vswitch wayfire-shell window-rules wobbly wm-actions xdg-activation vswipe preserve-output scale
vwidth = 4

[input]
cursor_theme = Breeze_Light
disable_touchpad_while_typing = true
xkb_variant = altgr-intl

[output]
scale = 1.250000
vrr = true

[vswipe]
fingers = 3

[wm-actions]
toggle_showdesktop = <super> KEY_D

[workarounds]
auto_reload_config = true
use_external_output_configuration = true

