Gtk/CursorThemeName "Breeze_Light"
Gtk/DecorationLayout "menu:minimize,maximize,close"
Gtk/EnableAnimations 1
Gtk/EnablePrimaryPaste 0
Gtk/TitlebarDoubleClick "toggle-maximize"
Gtk/TitlebarMiddleClick "none"
Gtk/TitlebarRightClick "menu"
